# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: name-tests-test
    -   id: check-added-large-files
-   repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: [--profile=black]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: venv,tests
        additional_dependencies: [types-docutils==0.20.0.3, types-requests==2.31.0.6, types-setuptools==68.2.0.0, types-urllib3==1.26.25.14]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        stages: [manual]
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
